desc "Generates a Utility Bill PDF"

task :console do
  sh "irb -r./form_letter"
end

task :build do
  sh "ruby form_letter.rb"
end

task :test do
  abort "No tests yet! Fix me please..."
end

task :default => :build
